name: Docker Image CI - alpine-mpd

on:
  push:
    branches:
      - master
    paths:
      - "alpine-mpd/*"

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Build and publish "latest" Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.PAT_GHCR }}
        image-name: alpine-mpd
        dockerfile: Dockerfile
        build-context: ./alpine-mpd
